### PR TITLE
Assorted housekeeping

### PR DESCRIPTION
**Pull request by mswilkison**
This PR makes assorted updates and corrections to the website.

* Pins "source-map": "^0.8.0-beta.0" in package.json as I could not get the site to compile with node v18 otherwise (maybe someone better with node can recommend a better approach)
* Removes any reference to existing tBTC liquidity pools due to the imminent shutdown of renBTC and pending deployment of new pools without such exposure
* Updates various links to point to threshold docs instead of legacy nucypher docs
* Adds Balancer T + ETH pools
* Fixes description of Threshold governace
* Fixes some vote delegation links + staker vs token holder logic
*

### CODE REVIEW

**Comment by liz-shinn** [comment]
Nice! Thanks Maclane!

**Comment by mswilkison** [comment]
Rebased this PR to squash the commit log and remove any dependency changes. Not sure why the deploy preview check is failing since it's just content changes?

**Comment by georgeweiler** [comment]
The changes look fine. I pinged @michalinacienciala  to check on the pipeline.  Thanks @mswilkison !

**Comment by georgeweiler** [comment]
@mswilkison one guess is that it's because your commit is not signed?

**Comment by mswilkison** [comment]
> @mswilkison one guess is that it's because your commit is not signed/verified?

Signed and force pushed, but no dice.

**Comment by mswilkison** [comment]
:/ I rebased and resolved conflicts with the latest PR that was just merged, but still failing.

This PR removes links to several renBTC exposed pools so it'd be good if we can get it resolved and merged in, otherwise we are quasi-endorsing pools that are going to get people rekt.

**Comment by r-czajkowski** [comment]
> :/ I rebased and resolved conflicts with the latest PR that was just merged, but still failing.

Maybe because it's a PR from your fork repo 🤔 @mswilkison do you mind if I cherry-pick your commit and open a separate PR? Will probably be easier than investigating why it fails.

**Comment by mswilkison** [comment]
> > :/ I rebased and resolved conflicts with the latest PR that was just merged, but still failing.
> 
> Maybe because it's a PR from your fork repo 🤔 @mswilkison do you mind if I cherry-pick your commit and open a separate PR? Will probably be easier than investigating why it fails.

Sure, that's fine with me

**Comment by r-czajkowski** [comment]
Created a separate PR due to failing build see #65.

**Pull request closed without merging**
